-- AlterTable
ALTER TABLE "BingoTile" ADD COLUMN     "pointsPerSubmission" DOUBLE PRECISION NOT NULL DEFAULT 1,
ALTER COLUMN "points" SET DEFAULT 1,
ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION;
